# Hybrid deployment: Deploy thrive-app-ui and trigger existing shop deployment
# This is triggered when thrive-app-ui repository is pushed

steps:
  # Step 1: Build and deploy thrive-app-ui (current repository)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-thrive-app-ui'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/thrive-app-ui:latest'
      - '.'

  # Step 2: Push thrive-app-ui image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-thrive-app-ui'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/thrive-app-ui:latest'
    waitFor: ['build-thrive-app-ui']

  # Step 3: Deploy thrive-app-ui to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy-thrive-app-ui'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'thrive-app-ui'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/thrive-app-ui:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-secrets=ENABLE_ASSISTANT_FUNCTIONS=ENABLE_ASSISTANT_FUNCTIONS:latest,NEXT_PUBLIC_APP_URL=NEXT_PUBLIC_APP_URL:latest,NEXT_PUBLIC_ENABLE_ASSISTANT_FUNCTIONS=NEXT_PUBLIC_ENABLE_ASSISTANT_FUNCTIONS:latest,NEXT_PUBLIC_SHOP_URL=NEXT_PUBLIC_SHOP_URL:latest,NODE_ENV=NODE_ENV:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,THRIVE_CHAT_ASSISTANT_ID=THRIVE_CHAT_ASSISTANT_ID:latest,THRIVE_GEMINI_API_KEY=THRIVE_GEMINI_API_KEY:latest,THRIVE_OPENAI_API_KEY=THRIVE_OPENAI_API_KEY:latest,THRIVE_PANTRY_ASSISTANT_ID=THRIVE_PANTRY_ASSISTANT_ID:latest,THRIVE_ROUTINE_ASSISTANT_ID=THRIVE_ROUTINE_ASSISTANT_ID:latest'
      - '--service-account=647294150154-compute@developer.gserviceaccount.com'
      - '--min-instances=0'
      - '--max-instances=100'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300s'
    waitFor: ['push-thrive-app-ui']

  # Step 4: Re-deploy the existing thrive-app-shop with latest image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'redeploy-thrive-app-shop'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'thrive-app-shop'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/thrive-app-shop:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--set-env-vars=NODE_ENV=production,NEXT_PUBLIC_APP_URL=https://www.thrive.app,NEXT_PUBLIC_SHOP_URL=https://shop.thrive.app,THRIVE_SHOPIFY_STORE_DOMAIN=2g1rga-ky.myshopify.com,NEXT_PUBLIC_THRIVE_SHOPIFY_STORE_DOMAIN=2g1rga-ky.myshopify.com'
      - '--set-secrets=THRIVE_SHOPIFY_API_KEY=THRIVE_SHOPIFY_API_KEY:latest,THRIVE_SHOPIFY_API_SECRET_KEY=THRIVE_SHOPIFY_API_SECRET_KEY:latest,THRIVE_SHOPIFY_STOREFRONT_API_TOKEN=THRIVE_SHOPIFY_STOREFRONT_API_TOKEN:latest,NEXT_PUBLIC_THRIVE_SHOPIFY_STOREFRONT_API_TOKEN=THRIVE_SHOPIFY_STOREFRONT_API_TOKEN:latest'
      - '--service-account=647294150154-compute@developer.gserviceaccount.com'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300s'
    waitFor: ['deploy-thrive-app-ui']

# Images built
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/thrive-app-ui:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'